name: Bump version

on:
  workflow_dispatch:
    branches:
      - master
#  push:
#    branches:
#      - 'master'
#    paths-ignore:
#      - 'VERSION'
#  pull_request:
#    branches:
#      - 'master'
#    paths-ignore:
#      - 'VERSION'

permissions:
  contents: write

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Bump version file
      uses: francktrouillez/auto-bump-version-file@v1
      with:
        file: 'VERSION'

    - name: Read version
      id: version
      uses: juliangruber/read-file-action@v1
      with:
        path: ./VERSION
        trim: true

    - name: Commit and push version file
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        message: Version ${{ steps.version.outputs.content }}
        branch: master
