name: Build and publish release

on:
  workflow_dispatch:
    branches:
      - master
#  push:
#    branches:
#      - 'master'
#  pull_request:
#    branches:
#      - 'master'

permissions:
  contents: write

jobs:
  build_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Bump version file
      uses: francktrouillez/auto-bump-version-file@v1
      with:
        file: 'VERSION'

    - name: Read version
      id: version
      uses: juliangruber/read-file-action@v1
      with:
        path: ./VERSION
        trim: true

    - name: Build packages
      run: make all

    - name: Commit and push version file
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add VERSION
        git commit -m "Version ${{ steps.version.outputs.content }}"
        git tag -a v${{ steps.version.outputs.content }} -m "Version ${{ steps.version.outputs.content }}"
        git push origin v${{ steps.version.outputs.content }}
        git push

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.version.outputs.content }}
        release_name: Release v${{ steps.version.outputs.content }}
        draft: false
        prerelease: false

    - name: Upload Release mips
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./out/nfqws-keenetic_${{ steps.version.outputs.content }}_mips-3.4.ipk
        asset_name: nfqws-keenetic_mips.ipk
        asset_content_type: application/octet-stream

    - name: Upload Release mipsel
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./out/nfqws-keenetic_${{ steps.version.outputs.content }}_mipsel-3.4.ipk
        asset_name: nfqws-keenetic_mipsel.ipk
        asset_content_type: application/octet-stream

    - name: Upload Release aarch64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./out/nfqws-keenetic_${{ steps.version.outputs.content }}_aarch64-3.10.ipk
        asset_name: nfqws-keenetic_aarch64.ipk
        asset_content_type: application/octet-stream

    - name: Upload Release armv7
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./out/nfqws-keenetic_${{ steps.version.outputs.content }}_armv7-3.2.ipk
        asset_name: nfqws-keenetic_armv7.ipk
        asset_content_type: application/octet-stream
