name: Build and publish release

on:
  workflow_dispatch:
    branches:
      - master
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

permissions:
  contents: write

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Bump version file
      uses: francktrouillez/auto-bump-version-file@v1
      with:
        file: 'VERSION'

    - name: Read version
      id: version
      uses: juliangruber/read-file-action@v1
      with:
        path: ./VERSION
        trim: true

    - name: Commit and push version file
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        message: Version ${{ steps.version.outputs.content }}
        branch: master

  build_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Read version
      id: version
      uses: juliangruber/read-file-action@v1
      with:
        path: ./VERSION
        trim: true

    - name: Build packages
      run: make all

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.version.outputs.content }}
        release_name: Release v${{ steps.version.outputs.content }}
        draft: false
        prerelease: false

    - name: Upload Release mips
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./out/nfqws-keenetic_${{ steps.version.outputs.content }}_mips-3.4.ipk
        asset_name: nfqws-keenetic_${{ steps.version.outputs.content }}_mips-3.4.ipk
        asset_content_type: application/octet-stream

    - name: Upload Release mipsel
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./out/nfqws-keenetic_${{ steps.version.outputs.content }}_mipsel-3.4.ipk
        asset_name: nfqws-keenetic_${{ steps.version.outputs.content }}_mipsel-3.4.ipk
        asset_content_type: application/octet-stream

    - name: Upload Release aarch64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./out/nfqws-keenetic_${{ steps.version.outputs.content }}_aarch64-3.10.ipk
        asset_name: nfqws-keenetic_${{ steps.version.outputs.content }}_aarch64-3.10.ipk
        asset_content_type: application/octet-stream

    - name: Upload Release armv7
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./out/nfqws-keenetic_${{ steps.version.outputs.content }}_armv7-3.2.ipk
        asset_name: nfqws-keenetic_${{ steps.version.outputs.content }}_armv7-3.2.ipk
        asset_content_type: application/octet-stream
