name: Test target

on:
  workflow_dispatch:
    branches:
      - master

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test_target:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get binaries
      id: get_bins
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: 'bol-van/zapret'
        version: 'latest'
        regex: true
        file: "zapret-.*\\.tar.gz"
        target: 'zapret/'
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Show binaries
      run: |
        echo "Version: ${{ steps.get_bins.outputs.version }}"
        echo "Name: ${{ steps.get_bins.outputs.name }}"
        ls -la zapret/

